import {
  HomeIcon,
  ChartBarIcon,
  UsersIcon,
  CalendarDaysIcon,
  FolderIcon,
  BuildingOffice2Icon,
  ChatBubbleLeftRightIcon,
  BellIcon,
  UserIcon,
  UserGroupIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  ScaleIcon,
  DocumentTextIcon,
  FlagIcon,
  BriefcaseIcon,
  AcademicCapIcon,
  BanknotesIcon,
  InboxIcon,
  TrophyIcon,
  QuestionMarkCircleIcon,
  PrinterIcon,
  EnvelopeIcon,
  CheckIcon,
  ArrowUturnLeftIcon,
  LockClosedIcon,
  LockOpenIcon,
  ChevronDownIcon,
  HeartIcon,
  ShieldCheckIcon,
  GlobeAltIcon,
  TruckIcon,
  RocketLaunchIcon,
  CpuChipIcon,
  PaintBrushIcon,
  SparklesIcon,
  BeakerIcon,
  BoltIcon,
  CurrencyEuroIcon,
  DeviceTabletIcon,
  ComputerDesktopIcon,
  GlobeEuropeAfricaIcon,
  PencilSquareIcon,
  PhoneIcon,
  MapPinIcon,
  ClipboardDocumentIcon,
  TrashIcon,
  InformationCircleIcon,
} from "@heroicons/react/24/outline";

const ICON_MAP = {
  // core
  dashboard: HomeIcon,
  clipdocument: ClipboardDocumentIcon,
  stats: ChartBarIcon,
  users: UsersIcon,
  userGroup: UserGroupIcon,
  user: UserIcon,
  trash: TrashIcon,
  events: CalendarDaysIcon,
  documents: FolderIcon,
  messages: ChatBubbleLeftRightIcon,
  notifications: BellIcon,
  profile: UserIcon,
  info: InformationCircleIcon,
  courses: AcademicCapIcon,
  survey: InboxIcon,
  achievements: TrophyIcon,
  about: QuestionMarkCircleIcon,
  project: PrinterIcon,
  contact: EnvelopeIcon,
  phone: PhoneIcon,
  map: MapPinIcon,
  // institutions
  countries: BuildingOffice2Icon,
  ministry: BuildingOfficeIcon,
  parliament: BuildingLibraryIcon,
  scale: ScaleIcon,
  document: DocumentTextIcon,
  flag: FlagIcon,
  briefcase: BriefcaseIcon,
  banknotes: BanknotesIcon,
  factory: BuildingOfficeIcon,
  trophy: TrophyIcon,
  lighting: BoltIcon,
  euro: CurrencyEuroIcon,
  tablet: DeviceTabletIcon,
  computer: ComputerDesktopIcon,
  // missing FIXED
  globe: GlobeAltIcon,
  truck: TruckIcon,
  leaf: GlobeEuropeAfricaIcon,
  tractor: BeakerIcon,

  // actions
  check: CheckIcon,
  cancel: ArrowUturnLeftIcon,
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  dropdown: ChevronDownIcon,
  pencil: PencilSquareIcon,

  // thematic
  heart: HeartIcon,
  shield: ShieldCheckIcon,
  cpu: CpuChipIcon,
  paintbrush: PaintBrushIcon,
  sparkles: SparklesIcon,
  rocket: RocketLaunchIcon,
};

export default ICON_MAP;