import {
  HomeIcon,
  ChartBarIcon,
  UsersIcon,
  CalendarDaysIcon,
  FolderIcon,
  BuildingOffice2Icon,
  ChatBubbleLeftRightIcon,
  BellIcon,
  UserIcon,
  UserGroupIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  ScaleIcon,
  DocumentTextIcon,
  FlagIcon,
  BriefcaseIcon,
  AcademicCapIcon,
  BanknotesIcon,
  InboxIcon,
  TrophyIcon,
  QuestionMarkCircleIcon,
  PrinterIcon,
  EnvelopeIcon,
  CheckIcon,
  ArrowUturnLeftIcon,
  LockClosedIcon,
  LockOpenIcon,
  ChevronDownIcon,
  HeartIcon,
  ShieldCheckIcon,
  GlobeAltIcon,
  TruckIcon,
  RocketLaunchIcon,
  CpuChipIcon,
  PaintBrushIcon,
  SparklesIcon,
  BeakerIcon,
} from "@heroicons/react/24/outline";

const ICON_MAP = {
  // core
  dashboard: HomeIcon,
  stats: ChartBarIcon,
  users: UsersIcon,
  userGroup: UserGroupIcon,
  user: UserIcon,

  events: CalendarDaysIcon,
  documents: FolderIcon,
  messages: ChatBubbleLeftRightIcon,
  notifications: BellIcon,
  profile: UserIcon,

  courses: AcademicCapIcon,
  survey: InboxIcon,
  achievements: TrophyIcon,
  about: QuestionMarkCircleIcon,
  project: PrinterIcon,
  contact: EnvelopeIcon,

  // institutions
  countries: BuildingOffice2Icon,
  ministry: BuildingOfficeIcon,
  parliament: BuildingLibraryIcon,
  scale: ScaleIcon,
  document: DocumentTextIcon,
  flag: FlagIcon,
  briefcase: BriefcaseIcon,
  banknotes: BanknotesIcon,
  factory: BuildingOfficeIcon,
  trophy: TrophyIcon,
  // missing FIXED
  globe: GlobeAltIcon,
  truck: TruckIcon,
  leaf: SparklesIcon,
  tractor: BeakerIcon,

  // actions
  check: CheckIcon,
  cancel: ArrowUturnLeftIcon,
  lock: LockClosedIcon,
  unlock: LockOpenIcon,
  dropdown: ChevronDownIcon,

  // thematic
  heart: HeartIcon,
  shield: ShieldCheckIcon,
  cpu: CpuChipIcon,
  paintbrush: PaintBrushIcon,
  sparkles: SparklesIcon,
};

export default ICON_MAP;