
import {
    HomeIcon,
    BuildingOffice2Icon,
    ChartBarIcon,
    UsersIcon,
    CalendarDaysIcon,
    FolderIcon,
    ChatBubbleLeftRightIcon,
    BellIcon,
    UserGroupIcon,
    BuildingLibraryIcon,
    BuildingOfficeIcon,
    ScaleIcon,
    DocumentTextIcon,
    FlagIcon,
    UserIcon,
    BriefcaseIcon,
    AcademicCapIcon,
    BanknotesIcon,
    InboxIcon,
    TrophyIcon,
    QuestionMarkCircleIcon,
    PrinterIcon,
    EnvelopeIcon,
    CheckIcon, 
    ArrowUturnLeftIcon,
    LockClosedIcon, 
    LockOpenIcon,
    ChevronDownIcon
} from "@heroicons/react/24/outline";

const ICON_MAP = {
    dashboard: HomeIcon,
    countries: BuildingOffice2Icon,
    stats: ChartBarIcon,
    citiziens: UsersIcon,
    events: CalendarDaysIcon,
    documents: FolderIcon,
    messages: ChatBubbleLeftRightIcon,
    notifications: BellIcon,
    profil: UserIcon,
    courses: AcademicCapIcon,
    survey: InboxIcon,
    achievements: TrophyIcon,
    about: QuestionMarkCircleIcon,
    project: PrinterIcon,
    contact:EnvelopeIcon,
    AcademicCapIcon,
    UserIcon,
    UserGroupIcon,
    BuildingLibraryIcon,
    BuildingOfficeIcon,
    ScaleIcon,
    DocumentTextIcon,
    FlagIcon,
    BriefcaseIcon,
    BanknotesIcon,
    check: CheckIcon,
    cancel: ArrowUturnLeftIcon,
    lockClosed: LockClosedIcon,
    lockOpened: LockOpenIcon,
    downIcon: ChevronDownIcon
};

export default ICON_MAP;